### PR TITLE
add another implementation of websocket.  transfer data in json forma…

### PR DESCRIPTION
**Pull request by kexun**
1. add another implementation of websocket
2. transfer data in json format when using websocket protocal.
3. do not encode msg when using websocket protocal.

### CODE REVIEW

**Comment by sids-b** [comment]
cc @shouhong

**Comment by sids-b** [comment]
@kexun , I think we need to remove encode for QUIC as well
cc @sujithsimon22

**Comment by glenn-lg** [comment]
Look good to me

**Comment by kexun** [comment]
> @kexun , I think we need to remove encode for QUIC as well
> cc @sujithsimon22

we can not remove encode for QUIC.  because the quic protocol achieves multiplexing, encoding header helps to solve the problem of sticky and unpacking when multi stream connection.

**Comment by sujithsimon22** [comment]
> > @kexun , I think we need to remove encode for QUIC as well
> > cc @sujithsimon22
> 
> we can not remove encode for QUIC. because the quic protocol achieves multiplexing, encoding header helps to solve the problem of sticky and unpacking when multi stream connection.

Is it possible to alter the implementation of encode and decode functions, such that issue like https://github.com/kubeedge/kubeedge/issues/890 or  https://github.com/kubeedge/kubeedge/issues/889 are not caused while using QUIC protocol as well ?

**Review by sids-b — APPROVED** [review]

**Pull request merged**
